### ISSUE TITLE
なぜclf._decision_functionの符号を反転しているのでしょうか？

### ISSUE THREAD

**Issue by SAyaka0122** [shinmura0/Weakly-anomaly-detection#1]
素晴らしいコードの共有をありがとうございます。
一点、以下の部分でなぜdecision_functionの符号を反転しているのか分からなかったため、理由についてご教示いただけないでしょうか。
``
# plot the level sets of the decision function
    Z1 = -clf._decision_function(test_s)
    Z2 = -clf._decision_function(test_b)
``
どうぞよろしくお願いいたします。

**Comment by shinmura0** [comment]
本実装では、skelearnのLOFを使って異常スコアを出しています。
LOFでは、スコアが小さいほど異常度が高いのですが、AUCを出すために
わざわざスコアを反転しています。

従って、最終的にはスコアが大きいほど異常度が高いサンプルと
なっています。

**Comment by SAyaka0122** [comment]
早速ご回答いただきましてありがとうございました。承知致しました。
